### ISSUE TITLE
can you join our 351elec discord server? 

### ISSUE THREAD

**Issue by SzalikDesigns** [kefren68/es-theme-351ELEC-epicblanchenoir#1]
Join Our Community: https://discord.gg/bmXtCt88Tz

please join it and say hello on themes section, i will give you tips how to optimize theme, and what systems are missing or wrongly named

**Comment by kefren68** [comment]
Hi @szalik-rg351.
I'm already on discord.
About the theme, you are right.
Right now is not ready.
