### ISSUE TITLE
351v Scaling

### ISSUE THREAD

**Issue by joepistachio** [kefren68/es-theme-351ELEC-epicblanchenoir#2]
Looks great on the 3:2 view of the 351p/m but needs adjustment for the 4:3 view of the 351v

**Comment by kefren68** [comment]
Hi. It was designed for the Rg351p. I'm thinking to make a V version.

**Comment by kefren68** [comment]
Here there is the V version:

https://github.com/kefren68/es-theme-351ELEC-epicblanchenoir-V

I can't try it on a RG351V, so try it and tell me if anything is wrong

**Comment by joepistachio** [comment]
Just installed it and at first glance it looks really great! Thank you for all the hard work you did to create this, the black and white aesthetic is super classy.
